apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: llama2-70b-gbs1024-ckpt0-n64-1018t1221
  namespace: default
spec: 
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec: &job-spec
          terminationGracePeriodSeconds: 1
          containers:
          - args:
            - "export NODE_RANK=$RANK && unset RANK && \
               git clone --recursive https://github.com/sallylxl/deep_learning_examples.git /workspace/deep_learning_examples && \
               DEEP_LEARNING_EXAMPLES_DIR=/workspace/deep_learning_examples BASE_RESULTS_DIR=/workspace/deep_learning_examples/results      RUN_ID=1018t1221 GBS=1024 MBS=1 TP=4 PP=4  CP=0 MAX_STEPS=32      ENABLE_CKPT=0 UB_TP_COMM_OVERLAP=0 NFS=False      MOCK_DATA=1 DATA_DIR=/datasets/preset/bigscience/oscar-en      NCCL_IB_QPS_PER_CONNECTION= NUM_DLWORKERS=2      PYTHONPYCACHEPREFIX=None NCCL_IB_SL=3 EXPORT_METRICS=1      bash /workspace/deep_learning_examples/training/nemo/llm/llama2_70b_bf16/run_nemo_llama2_70b_bf16.sh"
            command:
            - /usr/bin/env
            - bash
            - -c
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TZ
              value: CST-8
            image: registry-ap-southeast.scitix.ai/hpc/nemo:24.07-sicl
            imagePullPolicy: Always 
            name: pytorch
            resources:
              limits:
                nvidia.com/gpu: "8"
              requests:
                nvidia.com/gpu: "8"
            securityContext:
              privileged: true
              capabilities:
                add:
                - IPC_LOCK
            volumeMounts:
            - mountPath: /dev/shm
              name: dev-shm
            - mountPath: /dev/infiniband
              name: ib
          volumes:
          - emptyDir:
              medium: Memory
            name: dev-shm
          - hostPath:
              path: /dev/infiniband
              type: ""
            name: ib
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: scitix.ai/gpu-type
                        operator: In
                        values:
                          - h100nvlink80
    Worker:
      replicas: 7
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          <<: *job-spec
