apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: meg-lm-llama2-70b-xlliu
  namespace: default
spec: 
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          labels:
            scitix.ai/topo-aware-in-node: "true"
        spec: &job-spec
          tolerations:
          - key: "scitix.ai/nodecheck"
            operator: "Exists"
            effect: "NoSchedule"
          containers:
          - args:
            - "export NODE_RANK=$RANK && unset RANK && \
               pip install /data/xlliu/siflowai/python/dist/siflowai-0.1.0-cp312-cp312-linux_x86_64.whl && \
               DEEP_LEARNING_EXAMPLES_DIR=/workspace/deep_learning_examples \
               BASE_RESULTS_DIR=/workspace/deep_learning_examples/results \
               RUN_ID=0 GBS=128 MBS=1 PP=4 TP=4 MAX_STEPS=1000 \
               ENABLE_CKPT=1 MOCK_DATA=true \
               bash /workspace/deep_learning_examples/training/Megatron-LM/llm/llama/run_meg_lm_llama2_70b_bf16.sh"
            command:
            - /usr/bin/env
            - bash
            - -c
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TZ
              value: CST-8
            image: registry-ap-southeast.scitix.ai/hpc/nemo:25.02.rc5
            imagePullPolicy: Always 
            name: pytorch
            resources:
              limits:
                cpu: "80"
                memory: 800Gi
                nvidia.com/gpu: "8"
                rdma/hca_shared_devices_all: "1"
              requests:
                cpu: "80"
                memory: 800Gi
                nvidia.com/gpu: "8"
                rdma/hca_shared_devices_all: "1"
            securityContext:
              capabilities:
                add:
                - IPC_LOCK
            volumeMounts:
            - mountPath: /dev/shm
              name: dev-shm
            - mountPath: /workspace/deep_learning_examples
              name: deep-learning-examples
            - mountPath: /data/xlliu/siflowai
              name: siflowai
          volumes:
          # - emptyDir:
          #     medium: Memory
          #   name: dev-shm
          - name: deep-learning-examples
            hostPath:
              path: /data/xlliu/deep_learning_examples
          - name: siflowai
            hostPath:
              path: /data/xlliu/siflowai
          - name: dev-shm
            hostPath:
              path: /dev/shm
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: scitix.ai/gpu-type
                        operator: In
                        values:
                          - h100nvlink80
    Worker:
      replicas: 3
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          labels:
            scitix.ai/topo-aware-in-node: "true"
        spec:
          <<: *job-spec
